CREATE TABLE USER (
  id   INTEGER IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(128) NOT NULL ,
  salt VARCHAR(128) NOT NULL ,
  mobile VARCHAR(20),
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX user_name ON USER (name);

CREATE TABLE ACCOUNT (
  id   INTEGER not null primary key auto_increment,
  user_id INTEGER NOT NULL ,
  name VARCHAR(50) NOT NULL ,
  balance INTEGER,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX account_name ON ACCOUNT (name);

CREATE TABLE PRODUCT (
  id   INTEGER IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL comment '商品名',
  price INTEGER comment '价格',
  stock INTEGER comment '库存',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX product_name ON PRODUCT (name);